### ISSUE TITLE
invalid parameter passed to hub when activating scene

### ISSUE THREAD

**Issue by etsinko** [sander76/aio-powerview-api#1]
This was tested on Home Assistant + aio-powerview-api 1.4
When a scene is activated scene id is passed to the hub using HTTP request. The parameter name should be `sceneId` instead of `sceneid`, otherwise hub does nothing. Please see `scenes.py`:

```python
    @asyncio.coroutine
    def activate_scene(self, scene_id: int):
        """Activate a scene

        :param scene_id: The id of the scene.
        :returns: Nothing.
        """
        yield from self.request.get(self._scenes_path, {"sceneid": scene_id})
```

I'm not sure if it works with older version of hub (black box). I have a new one (white round one) and it doesn't work.

**Comment by sander76** [comment]
@etsinko You must be one of the very first having the new hub!
I'll fix it asap.

**Comment by etsinko** [comment]
Thank you! I just got the hub yesterday.

**Comment by etsinko** [comment]
I also noticed that API has changed considerably from 1.4 Are you planning to update home assistant component to use new API?

**Comment by sander76** [comment]
@etsinko I don't have a real structured plan to do so. Fixing scene activation is priority. Updating other parts of the api will be incidentally I guess....

**Comment by etsinko** [comment]
I can look into this if you don't mind.

**Comment by sander76** [comment]
@etsinko Go ahead!

**Comment by sander76** [comment]
@etsinko 
Fix:
https://github.com/sander76/home-assistant/blob/powerview_update/homeassistant/components/scene/hunterdouglas_powerview.py

Not able to test yet. Will do a pr after that.

**Comment by etsinko** [comment]
@sander76 Thank you!

**Comment by etsinko** [comment]
@sander76 Which branch should I do my pull requests to? I noticed that you updated `master` with 1.5.3 but 1.5.3 had already been published from `moving_async_def` branch (70b2878f3376eaabb6c789167bc631610313553c)

Maybe both of these branches should be merged into one?

**Comment by sander76** [comment]
@etsinko I merged your pr into the async branch. Later I will merge that with master. (It has gotten a bit messy)

After that I think I am going to adopt the structure hass is using: master and dev branch.

Never really thought about this to be honest. If you have other suggestions: I am willing to learn.

Sander

**Comment by etsinko** [comment]
@sander76 I think HASS's `dev` for current work and `master` for releases is a good way to organize the project.
I can do PRs into `dev` and you can merge them as you feel. Once you have a critical mass for a new release you can merge `dev` into `master` and tag a new release.

With the current state I think you might have a couple of merge conflicts when you try to merge `moving_async_def` into `master` now.

**Comment by sander76** [comment]
@etsinko ok. Going for it!

**Comment by etsinko** [comment]
@sander76 I also wanted to ask you, where did you find API for PowerView? I can't find it anywhere online? Or did you reverse engineer it?

**Comment by sander76** [comment]
@etsinko Haha. I have inside information. I work for Hunter Douglas Europe. I'm the technical manager powerview on this side of the ocean... And a hobbyist programmer ;-)

**Comment by etsinko** [comment]
@sander76 Ah! Gotcha! It's good that you decided to implement this project then!

**Comment by sander76** [comment]
@etsinko see here:

https://github.com/home-assistant/home-assistant/pull/9990
