### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [sander76/aio-powerview-api#12]
Could you please tag the source? This allows distributions to get the complete source from GitHub.

PyPi has 1.6.15 while the GitHub release are on 1.6.14.

Thanks

**Comment by fabaff** [comment]
For 1.6.15 no proper source tarballs are available on PyPI. Arch-depended archives and wheels are not the "first choice" of distributions.

**Comment by mweinelt** [comment]
Sadly 1.6.19 is also not available as a source distribution on PyPi.

**Comment by sander76** [comment]
@mweinelt It should be now.
