### ISSUE TITLE
Mocket does not work on windows

### ISSUE THREAD

**Issue by sander76** [sander76/aio-powerview-api#7]
It says Mocket is fully cross platform, but I can't get it to run on my windows 10 machine.
And I am not able to move to another platform (I wish I could).

I found this library:
https://github.com/pnuckowski/aioresponses

It should be too hard to replace Mocket by this one. Are you good with that ?

Sander.

**Comment by sander76** [comment]
@etsinko Please have a look...

**Comment by etsinko** [comment]
Weird, as far as I know mocket is written in pure python. I'll give it a look and see why it is not working. What kind of error do you get?

**Comment by sander76** [comment]
@etsinko cffi installation error. I installed a compiled binary as a possible solution, but that resulted in a wrong version of cffi

**Comment by etsinko** [comment]
Weird, I have just installed python 3.5.4 on my windows 7 box and installed `mocket`. No problem whatsoever:
```
c:\Python35\Scripts>pip install mocket
Collecting mocket
  Downloading mocket-2.1.0.tar.gz
Collecting python-magic (from mocket)
  Downloading python_magic-0.4.13-py2.py3-none-any.whl
Collecting six (from mocket)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting decorator (from mocket)
  Downloading decorator-4.1.2-py2.py3-none-any.whl
Collecting hexdump (from mocket)
  Downloading hexdump-3.3.zip
Installing collected packages: python-magic, six, decorator, hexdump, mocket
  Running setup.py install for hexdump ... done
  Running setup.py install for mocket ... done
Successfully installed decorator-4.1.2 hexdump-3.3 mocket-2.1.0 python-magic-0.4
.13 six-1.11.0

c:\Python35\Scripts>
```

**Comment by sander76** [comment]
@etsinko hmmm.. weird. I retried, but can't fix it. Glad you could make the switch. I didn't really feel like having to fix this....

**Comment by etsinko** [comment]
No problem. We can add Travis CI integration so all unit testing is cared of by their service.
