### ISSUE TITLE
How to use this with home-assistant

### ISSUE THREAD

**Issue by pdwonline** [sander76/aio-powerview-api#9]
Can you help me how to use this with home assistant? Should I install it as a custom component?
ALso I am looking for a way to isssue the calibrate command. Ths powerview app does have this option, but I can't find it in the API

**Comment by sander76** [comment]
Just use this:

https://www.home-assistant.io/components/hunterdouglas_powerview/

The calibrate command is indeed not in this API. But feel free to do a PR.
